services:
  jenkins:
    build:
      context: ./jenkins
    container_name: luxora-jenkins
    user: root
    ports:
      - "${JENKINS_PORT:-8088}:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    restart: unless-stopped

volumes:
  jenkins-data:
